---

- hosts: localhost
  gather_facts: false
# Vars
  vars:
    ssh_timeout_interval: 20000

# tasks
  tasks:
  - name: set SSH timeout
    tags:
      - ansible_login
    become: true
    replace:
      path: /etc/ssh/sshd_config
      regexp: "(^ClientAliveInterval)(.*)$"
      replace: '\1 {{ssh_timeout_interval}}'
    notify: restart_sshd
  handlers:
    - name: restart_sshd
      service:
        name: sshd
        state: restarted